### ISSUE TITLE
Gelli keeps crashing at startup

### ISSUE THREAD

**Issue by rigrig** [dkanada/gelli#172]
What I was doing:
* Added some albums to my Jellyfin music library earlier that day
* Started downloading them onto Gelli
* While the download was still in progress: started playing one of the albums   
-> Got a toast "Couldn't play this song." and Gelli crashed

Now every time I launch Gelli I get a toast with "Couldn't play this song." and Gelli crashes immediately.
Force-stopping did not help.

This happened once before a while ago (not sure if it was even this version), clearing app storage fixed it but I neglected to report it.  I'll keep it broken for a while this time in case there is some more debug info that can be pried out of it. (And secretly hoping that the next version fixes it so I won't have to re-download a bunch of songs ;-)

Gelli version: 1.3.2
Server version: 10.7.6
Android version: 11 (LineageOS 18.1-202106140NIGHTLY-oneplus3 with MindTheGapps 11.0.0-arm64-20210328_143848 on a OnePlus 3T)
Cache size: 4296 files / 14G (from `/data/user/0/com.dkanada.gramophone/cache/music`)

<details><summary>adb log (<code>adb logcat -d | fgrep 12136</code>)</summary>

```
06-20 12:42:19.718  2288  2288 D Zygote  : Forked child process 12136
06-20 12:42:19.724  3029  3075 I ActivityManager: Start proc 12136:com.dkanada.gramophone/u0a273 for service {com.dkanada.gramophone/com.dkanada.gramophone.service.LoginService}
06-20 12:42:19.747 12136 12136 E nada.gramophon: Not starting debugger since process cannot load the jdwp agent.
06-20 12:42:19.846 12136 12136 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
06-20 12:42:19.848 12136 12136 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
06-20 12:42:19.858 12136 12136 W nada.gramophon: Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (greylist-max-o, reflection, denied)
06-20 12:42:19.858 12136 12136 W nada.gramophon: Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
06-20 12:42:19.859 12136 12136 W nada.gramophon: Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
06-20 12:42:19.904 12136 12136 D com.dkanada.gramophone.App: Adding request to queue: https://jellyfin.tubul.net/System/Info?format=json
06-20 12:42:20.312 12136 12136 I com.dkanada.gramophone.App: Response received from: https://jellyfin.tubul.net/System/Info?format=json
06-20 12:42:20.318 12136 12136 D com.dkanada.gramophone.App: Creating ApiWebSocket
06-20 12:42:20.319 12136 12136 D com.dkanada.gramophone.App: Connecting to web socket url: wss://jellyfin.tubul.net/socket?api_key=f74f64e72ced41c98c2696877fa12aa9&deviceId=d6d945e21ef1b211
06-20 12:42:20.321 12136 12136 W System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
06-20 12:42:20.321 12136 12136 W System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
06-20 12:42:20.321 12136 12136 W System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
06-20 12:42:20.337 12136 12136 D com.dkanada.gramophone.App: Adding request to queue: https://jellyfin.tubul.net/Sessions/Capabilities/Full
06-20 12:42:20.994 12136 12168 I com.dkanada.gramophone.App: Web socket connection opened.
06-20 12:42:21.054 12136 12168 D com.dkanada.gramophone.App: Web socket message received.
06-20 12:42:21.056 12136 12168 I com.dkanada.gramophone.App: Received web socket message: ForceKeepAlive
06-20 12:42:21.401 12136 12136 I com.dkanada.gramophone.App: Response received from: https://jellyfin.tubul.net/Sessions/Capabilities/Full
06-20 12:42:24.843 12136 12155 I nada.gramophon: Waiting for a blocking GC ProfileSaver
06-20 12:42:24.866 12136 12155 I nada.gramophon: WaitForGcToComplete blocked ProfileSaver on AddRemoveAppImageSpace for 22.787ms
06-20 12:42:37.568 12136 12136 D com.dkanada.gramophone.App: Adding request to queue: https://jellyfin.tubul.net/System/Info?format=json
06-20 12:42:37.579 12136 12180 I AdrenoGLES: QUALCOMM build                   : 7331a27, Ieeb4a86f7b
06-20 12:42:37.579 12136 12180 I AdrenoGLES: Build Date                       : 11/13/19
06-20 12:42:37.579 12136 12180 I AdrenoGLES: OpenGL ES Shader Compiler Version: EV031.27.05.02
06-20 12:42:37.579 12136 12180 I AdrenoGLES: Local Branch                     : 
06-20 12:42:37.579 12136 12180 I AdrenoGLES: Remote Branch                    : 
06-20 12:42:37.579 12136 12180 I AdrenoGLES: Remote Branch                    : 
06-20 12:42:37.579 12136 12180 I AdrenoGLES: Reconstruct Branch               : 
06-20 12:42:37.579 12136 12180 I AdrenoGLES: Build Config                     : S L 8.0.12 AArch64
06-20 12:42:37.583 12136 12180 I AdrenoGLES: PFP: 0x005ff110, ME: 0x005ff066
06-20 12:42:37.599 12136 12180 I Gralloc4: mapper 4.x is not supported
06-20 12:42:37.599 12136 12180 W Gralloc3: mapper 3.x is not supported
06-20 12:42:37.611 12136 12136 I com.dkanada.gramophone.App: Response received from: https://jellyfin.tubul.net/System/Info?format=json
06-20 12:42:37.611 12136 12136 D com.dkanada.gramophone.App: Adding request to queue: https://jellyfin.tubul.net/Sessions/Capabilities/Full
06-20 12:42:37.661 12136 12136 I com.dkanada.gramophone.App: Response received from: https://jellyfin.tubul.net/Sessions/Capabilities/Full
06-20 12:42:38.638 12136 12136 W MaterialProgressBar: Non-support version of tint method called, this is error-prone and will crash below Lollipop if you are calling it as a method of ProgressBar instead of MaterialProgressBar
06-20 12:42:38.638 12136 12136 W MaterialProgressBar: Non-support version of tint method called, this is error-prone and will crash below Lollipop if you are calling it as a method of ProgressBar instead of MaterialProgressBar
06-20 12:42:38.645 12136 12136 D com.dkanada.gramophone.App: Adding request to queue: https://jellyfin.tubul.net/Users/60df2c7a8b3c46608ee4b81c98da49f2/Views?format=json
06-20 12:42:38.739 12136 12136 I TetheringManager: registerTetheringEventCallback:com.dkanada.gramophone
06-20 12:42:38.743 12136 12136 I ExoPlayerImpl: Init cc89441 [ExoPlayerLib/2.12.2] [OnePlus3T, ONEPLUS A3003, OnePlus, 30]
06-20 12:42:38.750 12136 12136 I LocalPlayer: onPlaybackStateChanged: 4
06-20 12:42:38.765 12136 12136 I com.dkanada.gramophone.App: Response received from: https://jellyfin.tubul.net/Users/60df2c7a8b3c46608ee4b81c98da49f2/Views?format=json
06-20 12:42:38.784 12136 12192 W SimpleExoPlayer: Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
06-20 12:42:38.784 12136 12192 W SimpleExoPlayer:   java.lang.IllegalStateException
06-20 12:42:38.784 12136 12192 W SimpleExoPlayer:       at com.google.android.exoplayer2.SimpleExoPlayer.verifyApplicationThread(SimpleExoPlayer.java:3)
06-20 12:42:38.784 12136 12192 W SimpleExoPlayer:       at com.google.android.exoplayer2.SimpleExoPlayer.getCurrentTimeline(SimpleExoPlayer.java:1)
06-20 12:42:38.784 12136 12192 W SimpleExoPlayer:       at com.google.android.exoplayer2.BasePlayer.getCurrentMediaItem(BasePlayer.java:1)
06-20 12:42:38.784 12136 12192 W SimpleExoPlayer:       at com.dkanada.gramophone.service.playback.LocalPlayer.setDataSource(LocalPlayer.java:1)
06-20 12:42:38.784 12136 12192 W SimpleExoPlayer:       at com.dkanada.gramophone.service.MusicService.openCurrent(MusicService.java:3)
06-20 12:42:38.784 12136 12192 W SimpleExoPlayer:       at com.dkanada.gramophone.service.MusicService.restoreQueuesAndPositionIfNecessary(MusicService.java:10)
06-20 12:42:38.784 12136 12192 W SimpleExoPlayer:       at com.dkanada.gramophone.service.MusicService.access$500(MusicService.java:1)
06-20 12:42:38.784 12136 12192 W SimpleExoPlayer:       at com.dkanada.gramophone.service.MusicService$QueueHandler.handleMessage(MusicService.java:3)
06-20 12:42:38.784 12136 12192 W SimpleExoPlayer:       at android.os.Handler.dispatchMessage(Handler.java:106)
06-20 12:42:38.784 12136 12192 W SimpleExoPlayer:       at android.os.Looper.loop(Looper.java:223)
06-20 12:42:38.784 12136 12192 W SimpleExoPlayer:       at android.os.HandlerThread.run(HandlerThread.java:67)
06-20 12:42:38.785 12136 12192 W SimpleExoPlayer: Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
06-20 12:42:38.786 12136 12192 W SimpleExoPlayer: Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
06-20 12:42:38.786 12136 12192 I LocalPlayer: onMediaItemTransition: com.google.android.exoplayer2.MediaItem@e7aa316f 3
06-20 12:42:38.786 12136 12192 W SimpleExoPlayer: Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
06-20 12:42:38.789 12136 12192 W SimpleExoPlayer: Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
06-20 12:42:38.790 12136 12192 I LocalPlayer: onPositionDiscontinuity: 1
06-20 12:42:38.790 12136 12192 W SimpleExoPlayer: Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
06-20 12:42:38.790 12136 12192 I chatty  : uid=10273(com.dkanada.gramophone) identical 20 lines
06-20 12:42:38.790 12136 12192 W SimpleExoPlayer: Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
06-20 12:42:38.791 12136 12191 D com.dkanada.gramophone.App: Adding request to queue: https://jellyfin.tubul.net/Sessions/Playing
06-20 12:42:38.791 12136 12192 I LocalPlayer: onPlaybackStateChanged: 2
06-20 12:42:38.791 12136 12192 W SimpleExoPlayer: Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
06-20 12:42:38.835 12136 12192 W SimpleExoPlayer: Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
06-20 12:42:38.835 12136 12190 W SimpleExoPlayer: Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
06-20 12:42:38.837 12136 12190 I com.dkanada.gramophone.util.MusicUtil: playing audio: https://jellyfin.tubul.net/Audio/c2901f4b37435f523ee5e87328ba738b/universal?UserId=60df2c7a8b3c46608ee4b81c98da49f2&DeviceId=d6d945e21ef1b211&MaxStreamingBitrate=10000000&Container=mp3|mp3,mka|opus,m4a|aac,ogg|vorbis,flac|flac,opus|opus,ogg|opus&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=f74f64e72ced41c98c2696877fa12aa9
06-20 12:42:38.837 12136 12190 W SimpleExoPlayer: Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
06-20 12:42:38.861 12136 12187 E ExoPlayerImplInternal: Playback error
06-20 12:42:38.861 12136 12187 E ExoPlayerImplInternal:   com.google.android.exoplayer2.ExoPlaybackException: Source error
06-20 12:42:38.861 12136 12187 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:37)
06-20 12:42:38.861 12136 12187 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
06-20 12:42:38.861 12136 12187 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:223)
06-20 12:42:38.861 12136 12187 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
06-20 12:42:38.861 12136 12187 E ExoPlayerImplInternal:   Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (OggExtractor, FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor) could read the stream.
06-20 12:42:38.861 12136 12187 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:21)
06-20 12:42:38.861 12136 12187 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:14)
06-20 12:42:38.861 12136 12187 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:6)
06-20 12:42:38.861 12136 12187 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-20 12:42:38.861 12136 12187 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-20 12:42:38.861 12136 12187 E ExoPlayerImplInternal:       at java.lang.Thread.run(Thread.java:923)
06-20 12:42:38.919 12136 12136 W TabLayout: MODE_SCROLLABLE + GRAVITY_FILL is not supported, GRAVITY_START will be used instead
06-20 12:42:38.938 12136 12136 D com.dkanada.gramophone.App: Adding request to queue: https://jellyfin.tubul.net/Users/60df2c7a8b3c46608ee4b81c98da49f2/Items?SortBy=Random&recursive=true&IncludeItemTypes=Audio&ParentId=7e64e319657a9516ec78490da03edccb&StartIndex=0&Fields=MediaSources&sortOrder=Descending&Limit=100&format=json
06-20 12:42:38.940 12136 12136 D com.dkanada.gramophone.App: Adding request to queue: https://jellyfin.tubul.net/Users/60df2c7a8b3c46608ee4b81c98da49f2/Items?ParentId=7e64e319657a9516ec78490da03edccb&StartIndex=0&recursive=true&Limit=100&IncludeItemTypes=Playlist&format=json
06-20 12:42:38.942 12136 12136 D com.dkanada.gramophone.App: Adding request to queue: https://jellyfin.tubul.net/Artists/AlbumArtists?ParentId=7e64e319657a9516ec78490da03edccb&StartIndex=0&SortBy=SortName&recursive=true&Fields=Genres&UserId=60df2c7a8b3c46608ee4b81c98da49f2&sortOrder=Ascending&Limit=100&format=json
06-20 12:42:38.944 12136 12136 D com.dkanada.gramophone.App: Adding request to queue: https://jellyfin.tubul.net/Users/60df2c7a8b3c46608ee4b81c98da49f2/Items?SortBy=Random&recursive=true&IncludeItemTypes=MusicAlbum&ParentId=7e64e319657a9516ec78490da03edccb&StartIndex=0&sortOrder=Descending&Limit=100&format=json
06-20 12:42:38.947 12136 12136 D com.dkanada.gramophone.App: Adding request to queue: https://jellyfin.tubul.net/Users/60df2c7a8b3c46608ee4b81c98da49f2/Items?SortBy=Random&recursive=true&Filters=IsFavorite&IncludeItemTypes=Audio&ParentId=7e64e319657a9516ec78490da03edccb&StartIndex=0&Fields=MediaSources&sortOrder=Descending&Limit=100&format=json
06-20 12:42:39.016 12136 12136 I LocalPlayer: onPlayerError: Source error
06-20 12:42:39.018 12136 12136 D CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10273; state: ENABLED
06-20 12:42:39.023 12136 12136 I LocalPlayer: onPlaybackStateChanged: 1
06-20 12:42:39.036 12136 12136 I LocalPlayer: onMediaItemTransition: null 3
06-20 12:42:39.037 12136 12136 I LocalPlayer: onPlaybackStateChanged: 4
06-20 12:42:39.037 12136 12191 D com.dkanada.gramophone.App: Adding request to queue: https://jellyfin.tubul.net/Sessions/Playing
06-20 12:42:39.223 12136 12136 W MaterialProgressBar: Non-support version of tint method called, this is error-prone and will crash below Lollipop if you are calling it as a method of ProgressBar instead of MaterialProgressBar
06-20 12:42:39.223 12136 12136 W MaterialProgressBar: Drawable did not implement TintableDrawable, it won't be tinted below Lollipop
06-20 12:42:39.223 12136 12136 W MaterialProgressBar: Non-support version of tint method called, this is error-prone and will crash below Lollipop if you are calling it as a method of ProgressBar instead of MaterialProgressBar
06-20 12:42:39.834 12136 12136 I com.dkanada.gramophone.App: Response received from: https://jellyfin.tubul.net/Sessions/Playing
06-20 12:42:39.851 12136 12136 I com.dkanada.gramophone.App: Response received from: https://jellyfin.tubul.net/Artists/AlbumArtists?ParentId=7e64e319657a9516ec78490da03edccb&StartIndex=0&SortBy=SortName&recursive=true&Fields=Genres&UserId=60df2c7a8b3c46608ee4b81c98da49f2&sortOrder=Ascending&Limit=100&format=json
06-20 12:42:39.871 12136 12190 E AndroidRuntime: FATAL EXCEPTION: com.dkanada.gramophone.service.MusicService$PlaybackHandler
06-20 12:42:39.871 12136 12190 E AndroidRuntime: Process: com.dkanada.gramophone, PID: 12136
06-20 12:42:39.871 12136 12190 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
06-20 12:42:39.871 12136 12190 E AndroidRuntime: 	at java.util.ArrayList.add(ArrayList.java:483)
06-20 12:42:39.871 12136 12190 E AndroidRuntime: 	at com.google.android.exoplayer2.ExoPlayerImpl.addMediaSourceHolders(ExoPlayerImpl.java:8)
06-20 12:42:39.871 12136 12190 E AndroidRuntime: 	at com.google.android.exoplayer2.ExoPlayerImpl.addMediaSources(ExoPlayerImpl.java:5)
06-20 12:42:39.871 12136 12190 E AndroidRuntime: 	at com.google.android.exoplayer2.ExoPlayerImpl.addMediaItems(ExoPlayerImpl.java:2)
06-20 12:42:39.871 12136 12190 E AndroidRuntime: 	at com.google.android.exoplayer2.ExoPlayerImpl.addMediaItems(ExoPlayerImpl.java:1)
06-20 12:42:39.871 12136 12190 E AndroidRuntime: 	at com.google.android.exoplayer2.BasePlayer.addMediaItem(BasePlayer.java:1)
06-20 12:42:39.871 12136 12190 E AndroidRuntime: 	at com.google.android.exoplayer2.SimpleExoPlayer.addMediaItem(SimpleExoPlayer.java:2)
06-20 12:42:39.871 12136 12190 E AndroidRuntime: 	at com.dkanada.gramophone.service.playback.LocalPlayer.appendDataSource(LocalPlayer.java:7)
06-20 12:42:39.871 12136 12190 E AndroidRuntime: 	at com.dkanada.gramophone.service.playback.LocalPlayer.queueDataSource(LocalPlayer.java:3)
06-20 12:42:39.871 12136 12190 E AndroidRuntime: 	at com.dkanada.gramophone.service.MusicService.prepareNextImpl(MusicService.java:4)
06-20 12:42:39.871 12136 12190 E AndroidRuntime: 	at com.dkanada.gramophone.service.MusicService.access$1300(MusicService.java:1)
06-20 12:42:39.871 12136 12190 E AndroidRuntime: 	at com.dkanada.gramophone.service.MusicService$PlaybackHandler.handleMessage(MusicService.java:29)
06-20 12:42:39.871 12136 12190 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-20 12:42:39.871 12136 12190 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
06-20 12:42:39.871 12136 12190 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
06-20 12:42:39.991 12136 12168 D com.dkanada.gramophone.App: Web socket message received.
06-20 12:42:39.992 12136 12168 I com.dkanada.gramophone.App: Received web socket message: UserDataChanged
06-20 12:42:39.994 12136 12168 I EventListener: onUserDataChanged
06-20 12:42:40.040 12136 12136 I com.dkanada.gramophone.App: Response received from: https://jellyfin.tubul.net/Users/60df2c7a8b3c46608ee4b81c98da49f2/Items?ParentId=7e64e319657a9516ec78490da03edccb&StartIndex=0&recursive=true&Limit=100&IncludeItemTypes=Playlist&format=json
06-20 12:42:42.406 12136 12136 I com.dkanada.gramophone.App: Response received from: https://jellyfin.tubul.net/Users/60df2c7a8b3c46608ee4b81c98da49f2/Items?SortBy=Random&recursive=true&Filters=IsFavorite&IncludeItemTypes=Audio&ParentId=7e64e319657a9516ec78490da03edccb&StartIndex=0&Fields=MediaSources&sortOrder=Descending&Limit=100&format=json
06-20 12:42:42.454 12136 12136 I com.dkanada.gramophone.App: Response received from: https://jellyfin.tubul.net/Users/60df2c7a8b3c46608ee4b81c98da49f2/Items?SortBy=Random&recursive=true&IncludeItemTypes=MusicAlbum&ParentId=7e64e319657a9516ec78490da03edccb&StartIndex=0&sortOrder=Descending&Limit=100&format=json
06-20 12:42:42.490 12136 12161 D Volley  : [968] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] https://jellyfin.tubul.net/Users/60df2c7a8b3c46608ee4b81c98da49f2/Items?SortBy=Random&recursive=true&IncludeItemTypes=Audio&ParentId=7e64e319657a9516ec78490da03edccb&StartIndex=0&Fields=MediaSources&sortOrder=Descending&Limit=100&format=json 0xd1a179c6 NORMAL 7> [lifetime=3551], [size=304591], [rc=200], [retryCount=0]
06-20 12:42:42.514 12136 12136 I com.dkanada.gramophone.App: Response received from: https://jellyfin.tubul.net/Users/60df2c7a8b3c46608ee4b81c98da49f2/Items?SortBy=Random&recursive=true&IncludeItemTypes=Audio&ParentId=7e64e319657a9516ec78490da03edccb&StartIndex=0&Fields=MediaSources&sortOrder=Descending&Limit=100&format=json
06-20 12:42:42.657 12136 12150 W System  : A resource failed to call release. 
06-20 12:42:43.952 12136 12160 D Volley  : [967] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] https://jellyfin.tubul.net/Sessions/Playing 0xd1a179c6 NORMAL 12> [lifetime=4077], [size=0], [rc=204], [retryCount=0]
06-20 12:42:43.970 12136 12136 I com.dkanada.gramophone.App: Response received from: https://jellyfin.tubul.net/Sessions/Playing
06-20 12:42:44.026 12136 12168 D com.dkanada.gramophone.App: Web socket message received.
06-20 12:42:44.028 12136 12168 I com.dkanada.gramophone.App: Received web socket message: UserDataChanged
06-20 12:42:44.030 12136 12168 I EventListener: onUserDataChanged
06-20 12:42:45.150  3029  3047 I ActivityManager: Killing 12136:com.dkanada.gramophone/u0a273 (adj 905): crash
06-20 12:42:45.223  3029  3064 W ActivityManager: setHasOverlayUi called on unknown pid: 12136
06-20 12:42:45.286  2288  2288 I Zygote  : Process 12136 exited due to signal 9 (Killed)
```
</details>

**Comment by rigrig** [comment]
Managed to repair it on my phone by (very quickly) opening the app, open the currently playing drawer, and selecting "clear queue" from the top-right menu. After that it works fine again.   
So it looks like something about a particular song is giving Gelli problems, and it tried to reload it on startup.

**Comment by brandonssmith** [comment]
I am having the same issue on my phone and I have almost the exact same specs. I know I shouldn't pre-diagnose but perhaps it had something to do with Android 11.

I'll attempt your fix and see what happens.

**Comment by dkanada** [comment]
I believe this was due to a database concurrency issue fixed in the latest update, so I'll close it for now but please comment here if you still experience it after the 1.3.4 release.
