### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by ReimuNotMoe** [dkanada/gelli#191]
OS: Android 10.0

When I typed all the login information and clicked on login, the screen will go white, after a while, it will show the login screen again.

Here are the logs:

```
09-29 00:38:37.893 16418 16418 I com.dkanada.gramophone.App: Response received from: http://172.16.24.8:8096/Users/AuthenticateByName?format=json
09-29 00:38:37.917 16418 16418 E AndroidRuntime: FATAL EXCEPTION: main
09-29 00:38:37.917 16418 16418 E AndroidRuntime: Process: com.dkanada.gramophone, PID: 16418
09-29 00:38:37.917 16418 16418 E AndroidRuntime: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:13)
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	at com.google.gson.Gson.fromJson(Gson.java:13)
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	at com.google.gson.Gson.fromJson(Gson.java:6)
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	at com.google.gson.Gson.fromJson(Gson.java:4)
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	at com.google.gson.Gson.fromJson(Gson.java:1)
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	at org.jellyfin.apiclient.serialization.GsonJsonSerializer.DeserializeFromString(GsonJsonSerializer.java:1)
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	at org.jellyfin.apiclient.interaction.BaseApiClient.DeserializeFromString(BaseApiClient.java:1)
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	at org.jellyfin.apiclient.interaction.ApiClient$1.onResponse(ApiClient.java:2)
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	at org.jellyfin.apiclient.interaction.ApiClient$1.onResponse(ApiClient.java:1)
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	at org.jellyfin.apiclient.interaction.ApiClientRequestListener.onResponse(ApiClientRequestListener.java:2)
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	at org.jellyfin.apiclient.interaction.ApiClientRequestListener.onResponse(ApiClientRequestListener.java:1)
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	at org.jellyfin.apiclient.interaction.VolleyResponseListener.onResponse(VolleyResponseListener.java:2)
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:5)
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:1)
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:4)
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7417)
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
09-29 00:38:37.917 16418 16418 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:5)
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:4)
09-29 00:38:37.917 16418 16418 E AndroidRuntime: 	... 21 more
09-29 00:38:37.919  1106 16604 W ActivityTaskManager:   Force finishing activity com.dkanada.gramophone/.activities.LoginActivity
```

**Comment by dkanada** [comment]
That's a very weird error message, is there anything in front of your server like a Cloudflare LB or reverse proxy?
