### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by tlc630** [dkanada/gelli#224]
I'm running android 4.4.4 (kitkat) on a hacked 1st gen Kindle (otterx).  All three available versions crash on startup (Gelli has stopped).  Would love to try this out.  How can I diagnose the issue. I'm new to debugging on android and would be thankful for any and all pointers

**Comment by jakobkukla** [comment]
If you are comfortable using adb you can use [adb logcat](https://developer.android.com/studio/command-line/logcat) to get a log file and post it here. There are also some logcat reader apps on the Play Store. There should be a stack trace from the crash in there.

**Comment by jakobkukla** [comment]
I was able to reproduce this running kitkat in the emulator. Not sure yet what the issue is though.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dkanada.gramophone.debug, PID: 2523
    java.lang.RuntimeException: Unable to get provider androidx.core.content.FileProvider: java.lang.ClassNotFoundException: Didn't find class "androidx.core.content.FileProvider" on path: DexPathList[[zip file "/data/app/com.dkanada.gramophone.debug-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.dkanada.gramophone.debug-1, /vendor/lib, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:4793)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4385)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4325)
        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.content.FileProvider" on path: DexPathList[[zip file "/data/app/com.dkanada.gramophone.debug-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.dkanada.gramophone.debug-1, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at android.app.ActivityThread.installProvider(ActivityThread.java:4778)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4385) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4325) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by tlc630** [comment]
Thanks for the update.  I never got that far in my debugging.  Hopefully and developer/maintainer will take a look.

**Comment by bgaesslein** [comment]
Making the App class extend MultiDexApplication makes it start up in a KitKat emulator but on login it crashes because apparently isIgnorBatteryOptimizations is not found (NoSuchMethodError).
Not sure if we can make it fully compatible with KitKat.

**Comment by tlc630** [comment]
Thanks for looking into this.  I have moved on from Jellyfin/gelli on my android boxes.
