### ISSUE TITLE
Launching the app from widget crashes the app

### ISSUE THREAD

**Issue by Nickbert7** [dkanada/gelli#31]
If you click on the widget to start the app, the app crashes/stopps.
Also the widgets are called phonograph: 
![Screenshot_20200705-093844_One UI Home](https://user-images.githubusercontent.com/14938497/86609367-2688c880-bfac-11ea-90c8-2fc34a425d4c.png)

**Comment by cowbe0x004** [comment]
Same with app crashing from widget. I use vpn to connect to jellyfin network. Crash seems to happen when I'm outside the network and it can't connect to jellyfin. Once in VPN, I have to open the app first, then the widget works.

**Comment by dkanada** [comment]
This should be resolved in the next update, but let me know if you still get crashes after that.

**Comment by Nickbert7** [comment]
For me the app still crashes when I want to launch it via the widget.
When the app is already running in the background, then it is working fine.

**Comment by strugee** [comment]
I can reproduce the behavior described in https://github.com/dkanada/gelli/issues/31#issuecomment-707819146 on a Pixel 3a XL running Android 11. Logs/stack trace:

```
02-15 14:41:01.766   938   938 D Zygote  : Forked child process 21664
02-15 14:41:01.771  1461  1561 I ActivityManager: Start proc 21664:com.dkanada.gramophone/u0a280 for pre-top-activity {com.dkanada.gramophone/com.dkanada.gramophone.ui.activities.MainActivity}
02-15 14:41:01.777   953  2999 D audio_hw_primary: out_write: retry previous failed cal level set
02-15 14:41:01.787 21664 21664 E nada.gramophon: Not starting debugger since process cannot load the jdwp agent.
02-15 14:41:01.836 21664 21664 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
02-15 14:41:01.837 21664 21664 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
02-15 14:41:01.904 21664 21664 D AndroidRuntime: Shutting down VM
02-15 14:41:01.904 21664 21664 E AndroidRuntime: FATAL EXCEPTION: main
02-15 14:41:01.904 21664 21664 E AndroidRuntime: Process: com.dkanada.gramophone, PID: 21664
02-15 14:41:01.904 21664 21664 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dkanada.gramophone/com.dkanada.gramophone.ui.activities.MainActivity}: java.lang.IllegalArgumentException: userId
02-15 14:41:01.904 21664 21664 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
02-15 14:41:01.904 21664 21664 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
02-15 14:41:01.904 21664 21664 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
02-15 14:41:01.904 21664 21664 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
02-15 14:41:01.904 21664 21664 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
02-15 14:41:01.904 21664 21664 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
02-15 14:41:01.904 21664 21664 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-15 14:41:01.904 21664 21664 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
02-15 14:41:01.904 21664 21664 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7660)
02-15 14:41:01.904 21664 21664 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-15 14:41:01.904 21664 21664 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-15 14:41:01.904 21664 21664 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
02-15 14:41:01.904 21664 21664 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: userId
02-15 14:41:01.904 21664 21664 E AndroidRuntime: 	at org.jellyfin.apiclient.interaction.ApiClient.GetUserViews(Unknown Source:41)
02-15 14:41:01.904 21664 21664 E AndroidRuntime: 	at com.dkanada.gramophone.util.QueryUtil.getLibraries(Unknown Source:17)
02-15 14:41:01.904 21664 21664 E AndroidRuntime: 	at com.dkanada.gramophone.ui.activities.MainActivity.onCreate(Unknown Source:33)
02-15 14:41:01.904 21664 21664 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8000)
02-15 14:41:01.904 21664 21664 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7984)
02-15 14:41:01.904 21664 21664 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
02-15 14:41:01.904 21664 21664 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
02-15 14:41:01.904 21664 21664 E AndroidRuntime: 	... 11 more
02-15 14:41:01.907  1461 21689 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
02-15 14:41:01.907  1461  2608 W ActivityTaskManager:   Force finishing activity com.dkanada.gramophone/.ui.activities.MainActivity
02-15 14:41:01.914  1461 21689 W DropBoxManagerService: Dropping: data_app_crash (1873 > 0 bytes)
```

**Comment by dkanada** [comment]
@Nickbert7 @strugee I believe the latest update should finally resolve this crash, but let me know if you ever see it again.
