### ISSUE TITLE
NullPointerException trying to invoke ApiClient.getApiUrl()

### ISSUE THREAD

**Issue by CappielloAntonio** [dkanada/gelli#58]
**What**
If Gelli is not killed manually by the user and the OS frees up memory, the app will crash next time the user will reopen it. This will happen generally after a night or resource-intensive task.

**Why**:
Normally, when Gelli starts, it goes to SplashActivity first anf then to LoginActivity or whatever else. Doing so, Gelli retrieve the apiClient and set it in App object.
If, for any reason, Gelli starts straight to any other activity but SplashActivity, there will be no apiClient to use in every request to the server, so the app will crash.

**How**:
- Install the app.
- Connect to server.
- Go home without killing Gelli.
- Fill the RAM and let the GC collect Gelli.
- Reopen it.

```
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jellyfin.apiclient.interaction.ApiClient.getApiUrl()' on a null object reference
stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jellyfin.apiclient.interaction.ApiClient.getApiUrl()' on a null object reference
	at com.dkanada.gramophone.util.MusicUtil.getSongFileUri(MusicUtil.java:32)
	at com.dkanada.gramophone.service.MusicService.getTrackUri(MusicService.java:169)
	at com.dkanada.gramophone.service.MusicService.openCurrent(MusicService.java:489)
	at com.dkanada.gramophone.service.MusicService.restoreQueuesAndPositionIfNecessary(MusicService.java:426)
	at com.dkanada.gramophone.service.MusicService.access$1300(MusicService.java:64)
	at com.dkanada.gramophone.service.MusicService$PlaybackHandler.handleMessage(MusicService.java:1211)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by dkanada** [comment]
I'm guessing this would be fixed by adding something to `onResume()` in the base activity.

**Comment by dkanada** [comment]
After a long wait, this crash should finally be resolved with the recent asynchronous authentication. Feel free to comment again if you every see it and we can reopen this issue though.
