### ISSUE TITLE
Playback does not start

### ISSUE THREAD

**Issue by JohnDowson** [dkanada/gelli#84]
Android 9 on Xiaomi Redmi S2.

Playback doesn't start, and tracks don't even seem to buffer.

This is server logs around attempted playback

```log
[2020-08-27 17:08:15.819 +03:00] [WRN] [98] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "192.168.1.79". Time (slow): 0:00:00.7111045. "http://192.168.1.78:8096/Audio/3c24fc6bfb6a91a08ea8fcb5f8fd5aaa/universal?UserId=c5ed203d70694898bb099ac2bf5e2cae&DeviceId=7c24541bf87b7bfd&MaxStreamingBitrate=10000000&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=mp3"
[2020-08-27 17:08:15.982 +03:00] [INF] [84] MediaBrowser.Api.Playback.MediaInfoService: GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 8000000, MaxStaticBitrate: 8000000, MusicStreamingTranscodingBitrate: 128000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [], TranscodingProfiles: [TranscodingProfile { Container: "ts", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }], ContainerProfiles: [], CodecProfiles: [], ResponseProfiles: [], SubtitleProfiles: [] }
[2020-08-27 17:08:16.466 +03:00] [INF] [84] MediaBrowser.Api.Playback.MediaInfoService: User policy for "JohnPhone". EnableAudioPlaybackTranscoding: True
[2020-08-27 17:08:16.468 +03:00] [INF] [84] MediaBrowser.Api.Playback.MediaInfoService: Profile: "Unknown Profile", No direct play profiles found for Path: "H:\Music\Amy LaVere\2011 - Stranger Me\01 - Damn Love Song.mp3"
[2020-08-27 17:08:16.469 +03:00] [INF] [84] MediaBrowser.Api.Playback.MediaInfoService: Profile: "Unknown Profile", No direct play profiles found for Path: "H:\Music\Amy LaVere\2011 - Stranger Me\01 - Damn Love Song.mp3"
[2020-08-27 17:08:16.471 +03:00] [INF] [84] MediaBrowser.Api.Playback.MediaInfoService: Profile: "Unknown Profile", No direct play profiles found for Path: "H:\Music\Amy LaVere\2011 - Stranger Me\01 - Damn Love Song.mp3"
[2020-08-27 17:08:16.479 +03:00] [WRN] [84] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "192.168.1.79". Time (slow): 0:00:00.5043744. "http://192.168.1.78:8096/Audio/62f6e6b418d3440a4278db60f985ed2e/universal?UserId=c5ed203d70694898bb099ac2bf5e2cae&DeviceId=7c24541bf87b7bfd&MaxStreamingBitrate=10000000&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=mp3"
[2020-08-27 17:08:16.865 +03:00] [INF] [73] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2020-08-27 17:08:28.866 +03:00] [INF] [73] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
[2020-08-27 17:08:39.764 +03:00] [WRN] [73] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "::1". Time (slow): 0:00:00.7340819. "http://localhost:8096/Sessions/Playing/Progress"
[2020-08-27 17:08:42.143 +03:00] [ERR] [73] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://192.168.1.78:8096/Items/85d25e15bd47150db5c9415552d89d71/Images/Primary?EnableImageEnhancers=true&MaxHeight=800"
MediaBrowser.Common.Extensions.ResourceNotFoundException: On Avery Island does not have an image of type Primary
   at MediaBrowser.Api.Images.ImageService.GetImage(ImageRequest request, Guid itemId, BaseItem item, Boolean isHeadRequest)
   at lambda_method(Closure , Object , Object )
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-08-27 17:08:42.564 +03:00] [ERR] [84] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://192.168.1.78:8096/Items/56fb6975193af0b35d4dc8edf77a419d/Images/Primary?EnableImageEnhancers=true&MaxHeight=800"
MediaBrowser.Common.Extensions.ResourceNotFoundException: Rock does not have an image of type Primary
   at MediaBrowser.Api.Images.ImageService.GetImage(ImageRequest request, Guid itemId, BaseItem item, Boolean isHeadRequest)
   at lambda_method(Closure , Object , Object )
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-08-27 17:08:59.604 +03:00] [WRN] [78] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "::1". Time (slow): 0:00:00.5750689. "http://localhost:8096/Sessions/Playing/Progress"
[2020-08-27 17:09:13.882 +03:00] [INF] [104] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS "::ffff:192.168.1.79" request
```

**Comment by dkanada** [comment]
Have you tried setting a bitrate limit in the app settings? If that works, it's an issue with direct playback.

**Comment by LouisH-760** [comment]
I am seeing this issue too, where if I try to direct play a flac file, playback will not start. Playing an mp3 file or forcing a transcode has playback starting fine.

**Comment by jakobkukla** [comment]
I'm experiencing a similar issue. When I try to direct play a file Gelli will crash and never open again unless reinstalled. When I limit the bitrate it works fine.

I'm on Android 11 and Jellyfin 10.7.0rc3

**Comment by donmega** [comment]
Same here on Android 11, Jellyfin 10.7.1
